version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: ./server/server.dockerfile
      target: development
    env_file: ./.env
    environment:
      - POSTGRES_HOST=postgres
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}
    tty: true
    volumes:
      - ./server:/app/server
  postgres:
    image: postgres:15.1
    env_file: ./.env
    ports: 
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: