export default () => ({
  SERVER_PORT: process.env?.SERVER_PORT,

  POSTGRES_HOST: process.env?.POSTGRES_HOST,
  POSTGRES_DB: process.env?.POSTGRES_DB,
  POSTGRES_USER: process.env?.POSTGRES_USER,
  POSTGRES_PASSWORD: process.env?.POSTGRES_PASSWORD,

  DATABRICKS_HOSTNAME: process.env?.DATABRICKS_HOSTNAME,
  DATABRICKS_HTTP_PATH: process.env?.DATABRICKS_HTTP_PATH,
  DATABRICKS_TOKEN: process.env?.DATABRICKS_TOKEN,
})